### ISSUE TITLE
Non-hosted plangular app looks for incorrect api endpoint

### ISSUE THREAD

**Issue by x20mar** [jxnblk/plangular#15]
I'm currently writing an angular web app, that when finished it would not be hosted on the web but instead be ran from their computers.

If you try to run plangular from a file, it will be unable to contact the soundcloud api, as it assumes that the soundcloud api is a file on your computer

    GET file://api.soundcloud.com/resolve.json?callback=angular.callbacks._1&client…3361983f16d2527b01fbf6408b7d7&url=http:%2F%2Fsoundcloud.com%2Fmrsjxn%2Fbbb net::ERR_FILE_NOT_FOUND 

To replicate, download master as a zip file, extract and run in your browser. Tested in both Chrome and Firefox

**Comment by jxnblk** [comment]
I don't think Angular is intended to run from a static file, and I don't plan to support doing so. Setting up a local server is probably a better way to handle this.
