### ISSUE TITLE
Updating current track title in playlist

### ISSUE THREAD

**Issue by lukephills** [jxnblk/plangular#17]
Hi how can I get the current playing track from the playlist example - not the playlist title.

Just using {{ track.title }} doesn't do anything. Any easy way to do this without lots of js?

Thanks

**Comment by scottwvw** [comment]
Hi jxnblk,

Forgive me for missing the obvious but I can't seem to get this to work, is there a code snippet to show the current track from a playlist (whether playing or paused)?

Also, thanks so much for the plugin, defo the best out there for me, just need this last bit to mean I can use it!

Thanks

Scott

**Comment by jxnblk** [comment]
I think the API has changed in the latest version. This should work to show the currently playing track title: `{{tracks[index].title}}` where `{{tracks[index]}}` is the currently playing track.

**Comment by scottwvw** [comment]
Aha, worked liked a charm, thanks!
