### ISSUE TITLE
Parse API responses pre-processed externally

### ISSUE THREAD

**Issue by mrbrainz** [jxnblk/plangular#29]
Love Plangular. Used it in a webapp I'm working on. The app uses Soundcloud's PHP API Wrapper to pull data from tracks. That means I'm essentially doubling the number of calls I'm making to the API by passing the permalink to Plangular when I could just straight pass meta that I've already pulled over cURL.

Your code is a doozy, and my lack of knowledge of how Vuejs works meant it blew my mind and I couldn't hack my way around the source to pass the Stream_URL.

Can you add some sort of support for external data sources being passed to the player to reduce calls to the API?

Cheers,

Greg

**Comment by jxnblk** [comment]
Closing this out as I don't plan on adding support for this in Plangular. (May implement something similar in a separate repo)
