### ISSUE TITLE
Using Plangular without Soundcloud

### ISSUE THREAD

**Issue by JeanHules** [jxnblk/plangular#44]
Hello,

Great player and great code. I am looking to use your player, but with MP3s. Is that possible? I have an API (/tracks.json) that I am pulling the song data from for my site. I have tried to rework some of the code so that the plangular attribute (src) is the mp3 file url which on the html is being generated by an ng-repeat that is pulling from the API. So my quick question is what would need to change to bypass the soundcloud api get, and just use the mp3 file url as the src?

Thanks

**Comment by jxnblk** [comment]
At the moment, Plangular isn't set up to do this, but I plan on working on an update that would work in this situation.
