### ISSUE TITLE
Semi continuous playback

### ISSUE THREAD

**Issue by akerd** [jxnblk/plangular#46]
Hi, I am looking into your solution and it seems very nice, but I have a question. I know that continous playback is not possible without involving AJAX or without using a popup window, but I would like to know if it is possible save the position inside the track and when a new page is loaded after a short break start again to play the track from the second it was.

Thank you in advance for the answer

**Comment by jxnblk** [comment]
Sorry for the slow response. This is completely possible using Angular or Vuejs. You'd just need to handle the routing in your own app. Saving play position could be handled with url parameters.
