### ISSUE TITLE
Plangular is not working on android device. Pls help me out

### ISSUE THREAD

**Issue by gabak** [jxnblk/plangular#47]
thanks for this great plugin, im developing a music app with ionic framework and i used plangular and it work very work on browser but doesnt work on android device, i will appreciate if you can help me out, thanks

**Comment by LeedleDev** [comment]
This may not be a problem with Plangular, android is rather temperamental with audio in my experiance. Your best bet is to ask on the Ionic Forums or look into the Cordova Media Plugin.

**Comment by jxnblk** [comment]
I don't think I have any better advice, sorry. Perhaps searching for help with using angular or vuejs on android could point you in the right direction.
