### ISSUE TITLE
Won't update upon updating URL

### ISSUE THREAD

**Issue by LeedleDev** [jxnblk/plangular#48]
Here is my code: 

    <div ng-repeat="url in darude track by $index">
    <div plangular="{{url}}">
      <p>{{ track.user.username }}</p>
      <h1>{{ track.title }}</h1>
      <button ng-click="playPause()">Play/Pause</button>
      
      <button ng-click="play()" ng-if="player.playing != track">Play</button>
      <button ng-click="pause()" ng-if="player.playing == track">Pause</button>

    </div>
</div>

When ever I try and update the URL value the player will not update as well.

**Comment by jxnblk** [comment]
Honestly, I'm not sure why this wouldn't work. Is `darude` just an array of urls for tracks?

It also looks like this example might be missing the closing tag...

**Comment by LeedleDev** [comment]
It's there, just not in the example. I think the problem is AJAX and incompatibility.

**Comment by jxnblk** [comment]
Are you using Angular's `$http` methods to update the array?

**Comment by LeedleDev** [comment]
yes

**Comment by jxnblk** [comment]
I can't duplicate this without more details. Please let me know if this is still an issue with the new version.
