### ISSUE TITLE
Pulling all/latest soundcloud tracks?

### ISSUE THREAD

**Issue by calv420** [jxnblk/plangular#49]
Hi, 

kinda new to github, but is there a way to pull like all of a users tracks in one go but have them as seperate tracks on the website. So like it is now I can pull a track but is there a way to pull them all automatically and then display as multiple tracks.

hope someone understands. Calvin.

**Comment by jxnblk** [comment]
At the moment I don't think this works. You can use playlists, but that would require managing that playlist on soundcloud.

I'm working on an update that should make what you're describing possible, but I'm not sure when I'll have time to work on it.
