### ISSUE TITLE
TypeError: Cannot read property 'tracks' of undefined

### ISSUE THREAD

**Issue by mombi93** [jxnblk/plangular#52]
I'm using plangular in my app and it works fine. However, when I navigate through the page and try to play the player I get the error mention mentioned in the above. This also happens in plangular example site in the angular section. Any idea why it's doing this?

**Comment by jxnblk** [comment]
It's hard to say what exactly is going on without seeing a more concrete example. The current version of Plangular is kinda wonky when it comes to routing. Hoping to fix that in the next version.
