### ISSUE TITLE
502 when access Soundcloud API

### ISSUE THREAD

**Issue by ptgamr** [jxnblk/plangular#54]
Hi, I know that this is not an issue with the library. But do you have any idea what is going on with SoundCloud API? Whenever I touch the API, I failed into errors like this:

![502 Error](http://i.imgur.com/5zaUcYX.png)

There is some occasions that it's ok for retrieving the Song information. After that, I got another 500 error when accessing the `stream_url`.

Damn!!

**Comment by jxnblk** [comment]
To be honest, I'm not really sure what it happening. I've definitely struggled a lot with the SoundCloud API in the past, so it's hard to say whether it's an issue with Plangular or with SoundCloud. I know there are some issues with the `/resolve` endpoint that Plangular uses and sometimes the URL scheme can cause things to not work as expected.

**Comment by jxnblk** [comment]
I'm unable to duplicate this without more details. Please let me know if this is still an issue in v3.
