### ISSUE TITLE
Can I list all comments below the player?

### ISSUE THREAD

**Issue by mrjcleaver** [jxnblk/plangular#56]
I want to list the comments vertically in a table below the playing track, such that clicking the comment will advance the player to the time of the comment.

Also, I would like the option to turn on/off autoplay from that point forward.

Thanks,
  Martin.

**Comment by mrjcleaver** [comment]
http://runnable.com/UuiVmRRoiBglAACt/get-a-tracks-comments-on-soundcloud-in-javascript

**Comment by jxnblk** [comment]
Plangular uses the [`/resolve` endpoint](https://developers.soundcloud.com/docs/api/reference#resolve), which doesn't seem to support comments. You'd have to write something custom to get those.
