### ISSUE TITLE
Seek not working in FireFox

### ISSUE THREAD

**Issue by lwigchert** [jxnblk/plangular#57]
Hi,

Currently there is an issue in FireFox with Plangular which doesn't allow you to seek in a track. The error is: "Error: Value being assigned to HTMLMediaElement.currentTime is not a finite floating-point value"

The error also occurs on the example page of Plangular itself.

Any idea how to solve this?

Thanks.

![plangular_error](https://cloud.githubusercontent.com/assets/10995812/6765556/a7dbd19a-cfdc-11e4-84e7-e171675b7fa5.png)

**Comment by philhudson91** [comment]
+1 this, I'm having the same issue

**Comment by philhudson91** [comment]
Looking at it, I think it's to do with this function here:

    seek: function(e) {
      if (!audio.readyState) return false;
      var xpos = e.offsetX / e.target.offsetWidth;
      audio.currentTime = (xpos * audio.duration);
    }

I've seen other similar plugins get around it using something like:

        //  Causes an Index size error in Firefox if you don't clamp the value
        if (value >= 0 && value <= 1)
        {
            this._volume = value;
            this._sound.volume = value;
        }

How could we apply it to this function so that it returns a valid FF compatibile value please?

**Comment by jxnblk** [comment]
I think this should be fixed with #36

**Comment by wamoyo** [comment]
I'm having the same issue with my custom controls. Would love to follow along here.
