### ISSUE TITLE
Global Player feature

### ISSUE THREAD

**Issue by shazzygh** [jxnblk/plangular#60]
Hey,
the v3 update breaks the global player functionality for me. Are there plans to include this feature in v3 or should I stick to v2? 

Thank you so much for developing this btw! It has easily become my favorite custom SC solution!
Best, shazzy

**Comment by jxnblk** [comment]
If you need the global player, you should stick to v2 for now.

I realized that it's sort of an anti-pattern to try to control things among many components, and I'm not sure how useful it would be to have a global player component. For my use-cases SoundCloud playlists achieve the same thing, but with fewer network requests.

For the time-being, I don't plan on including a global player in v3.

If you want to use a global player _and_ use v3, I think you should be able to handle that with a parent directive or controller.

**Comment by shazzygh** [comment]
Actually i am not so much interested in the "global" aspect of this feature, but only in the ability to build custom playlists outside of soundcloud by simply feeding a list of soundcloud links.

My current implementation (v2) feeds these soundcloud links through wordpress loops. To my understanding this functionality is not available anymore in v3 - or at least it is not obvious to a layman like me. If this is still possible without too much work, it would be awesome if you could include it as an example in the next update.
