### ISSUE TITLE
Including the 'Buy' button

### ISSUE THREAD

**Issue by cutout** [jxnblk/plangular#61]
I could hard-code this, but do you have plans to include Soundcloud's 'Buy' button in the player? As a sidenote, I'm really impressed with this project! Thanks for putting it out there.

**Comment by shazzygh** [comment]
Not the author here, but you can get display a Buy button like this:
`<a href="{{ track.purchase_url }}" ng-if="track.purchase_url" title="Buy">Buy</a>`

**Comment by cutout** [comment]
Great point, thanks shazzygh!
