### ISSUE TITLE
Player no longer working?

### ISSUE THREAD

**Issue by soulstrut** [jxnblk/plangular#67]
This is happening on my site as well as the Plangular site?

Did Soundcloud change something?

**Comment by shazzygh** [comment]
same here

**Comment by shazzygh** [comment]
fixed by changing client id
obtain here http://soundcloud.com/you/apps

**Comment by jxnblk** [comment]
Yes. Please use your own client id. Technically I shouldn't have one at all in the repo and I plan on removing the default one soon.

**Comment by soulstrut** [comment]
That worked.  Thank you!

**Comment by shnkng** [comment]
Do players using Vue.js work at all anymore?

**Comment by jxnblk** [comment]
@shnkng I dropped support for Vue.js in v3. The previous version has a hard-coded client id which **will not work anymore**. If you want to continue using the Vue.js version, you should fork the repo at that version and provide your own client id. You can register your own SoundCloud app here: https://developers.soundcloud.com/
