### ISSUE TITLE
'plangular' attribute is not observed

### ISSUE THREAD

**Issue by panamafrancis** [jxnblk/plangular#70]
If the plangular attribute is assigned like so...

```
<div plangular="{{myURL}}" > 
```

and the property 'myURL' changes, or in my case isn't available until the render is finished, the directive doesn't work. Is there a work-around to this?

**Comment by jxnblk** [comment]
There were issues like this with the previous version that I thought were working now. Let me take a look and get back to you.

**Comment by StillBreathing** [comment]
@jxnblk Apologies if I seem pushy, but any updates?

**Comment by judsonbomfim** [comment]
Any solution to this problem? I would love to use this plugin in my application

**Comment by judsonbomfim** [comment]
This project was abandoned? Long time no one answers ...

**Comment by jxnblk** [comment]
Sorry, I haven't been using Angular for months in my professional work and haven't had the time to look into this. I will still accept issues and pull requests but don't plan on working on this too much in the future, as it's fairly feature complete for the original design. I will update the docs to reflect this.

If you have any control over the technology used, I would highly recommend using React instead. FWIW, this looks like a better implementation of what Plangular does: https://github.com/soundblogs/react-soundplayer

**Comment by judsonbomfim** [comment]
Thank you!

**Comment by monsieurnebo** [comment]
I found a solution, just add `ng-if:"YOUR VARIABLE` in the plangular div :

`<div ng-if="myURL" plangular="{{ myURL }}" >`

Is that working for you too guys ?

**Comment by judsonbomfim** [comment]
Here it does not work at all.
I'm working with Ionic. The app is for Android

**Comment by judsonbomfim** [comment]
@monsieurnebo 
You can share the code (html and controller) to complete that you are using?
Thank you!

**Comment by judsonbomfim** [comment]
By upgrading this problem was solved for me!
Thanks!

But unfortunately for me remains another problem, I have also faced with other plugins which is the delay in the audio play of 10-15s.

If anyone can help
https://github.com/jxnblk/plangular/issues/77

**Comment by chauhanx** [comment]
Is there any solution to this??
