### ISSUE TITLE
An angular Error

### ISSUE THREAD

**Issue by NikosTsolakos** [jxnblk/plangular#73]
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/undefined/$injector/modulerr?p0=app&p1=Error:…p://nlmusic.cf/assets/js/sc-player/angular.min.js:32:427)

**Comment by bichiliad** [comment]
(Not a maintainer, but) I think that may be an issue with your code. Check that you've sourced it properly, and that you don't have any typos.
