### ISSUE TITLE
Pro accounts

### ISSUE THREAD

**Issue by sinedied** [jxnblk/plangular#76]
Hello, it seems that your directive is not working properly with soundcloud pro accounts, for example: https://soundcloud.com/hadrarecords/tracks

The tracks are listed properly, but no audio can be heard (a request to 'undefined' is made).

**Comment by shazzygh** [comment]
Are you using Safari by any chance?

**Comment by sinedied** [comment]
No, I currently test on chrome but I plan to use on android/ios.

I made further tests, and it seems some tracks work and some don't, it seems it may be a parsing issue.

If you use the link I provided in my first post, all the tracks from the first set do not work, and the ones from the second set works.

**Comment by shazzygh** [comment]
I don't think this has anything to do with pro accounts. I am using a plangular connected to different pro accounts and it works fine.

My guess is: As a pro user on soundcloud you have the option to disable streaming for each track. There is a checkbox called "streamable" somewhere. I think this option might be turned off for the set or songs in question.

**Comment by sinedied** [comment]
I will check that, thanks! But I might point just in case that the songs streams perfectly through the soundcloud website.

**Comment by jxnblk** [comment]
I think this is an issue with the `streamable` setting. Please check that option on tracks on soundcloud.com.
