### ISSUE TITLE
Question: controlling playback from a controller

### ISSUE THREAD

**Issue by angusfretwell** [jxnblk/plangular#78]
Hey,

I need to trigger playback in the player at an exact point in time (for synchronized playback of tracks across devices), so obviously need to send a play() event from a controller. How exactly would I do that? Seems like it should be fairly straightforward, but I'm pretty new to Angular.

Thanks in advance

**Comment by jxnblk** [comment]
I'm not entirely sure, but I think you could hook into the HTML audio element to set `currentTime`.
