### ISSUE TITLE
Prevent non-streamable tracks from being pulled into player

### ISSUE THREAD

**Issue by joshguss** [jxnblk/plangular#82]
Hello-

I know this repo is no longer actively maintained but I have been trying to figure this out on my own unsuccessfully and figured I would try and see if anyone here may have the answer...

I currently have a player built and setup to pull in a playlist, but if there are tracks in the given playlist which have been set to not streamable, the player will still pull in their info but just not play them. I am wondering if there is a way to set it up such that if using a playlist to populate the player, it can also be set to only pull in tracks where streamable is set to true within that playlist?

Thanks in advance!

**Comment by jxnblk** [comment]
I'm not sure I remember enough Angular off the top of my head, but I think you should be able to filter those out of an `ng-repeat` directive.
