### ISSUE TITLE
volume control

### ISSUE THREAD

**Issue by ZeoNish** [jxnblk/plangular#85]
Is it possible to add volume control?

**Comment by ZeoNish** [comment]
SOS...

**Comment by jxnblk** [comment]
Sorry, there's nothing built-in to Plangular for volume control, but you might be able to use the native JavaScript APIs https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/volume

**Comment by ZeoNish** [comment]
How you can implement it for your code?... I would be very grateful for your help.

ps. In vain have you stopped to develop the project.

**Comment by shazzygh** [comment]
Sorry to play the white knight, but @ZeoNish you need to ease up on your demands and "SOS"...

This project is clearly no longer maintained, it is offered free of charge and the developer kindly pointed you to a possible solution. Please have a little more respect for the time of others.
